name: Deploy With Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: docker build --no-cache -f Dockerfile -t pinomaker/jobscore:latest . --platform linux/arm64

      - name: Docker Push
        run: docker push pinomaker/jobscore:latest

      - name: SSH into Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Pull and run Docker image on Ubuntu
        run: |
          docker stop jobscore || true
          docker rm jobscore || true
          docker pull pinomaker/jobscore:latest
          docker run -d -p 3000:3000 --name jobscore pinomaker/jobscore
